# Generated by Django 3.2.7 on 2022-12-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='specalization',
            new_name='specialization',
        ),
    ]
